services:
  web:
    image: tomcat:9.0
    volumes:
      - ./webapp.war:/usr/local/tomcat/webapps/webapp.war
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service
    env_file:
      - .env

  node-service:
    build: ./api
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db
    expose:
      - "3000"
    env_file:
      - .env

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    build: ./db
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    env_file:
      - .env
